---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: content/scene/companies
  label: Companies
  create: all
  match: "**/*"
- type: directory
  path: content/scene/people
  label: People
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
upload_dir: media
public_path: https://res.cloudinary.com/schmopera/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
version: '0.52'
